# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b607638e772cede58f6d6ac0184f1b937a6f541e4e847841e49e03baabf71fe6d9968b091f5400aca9e8310596d815f1bcf7f70d1fc957744b1ace78140c8cf

test:
  secret_key_base: ac0d4c96e9f7cce7112e905f9b5d520613f9c554a6c0a2764684e3dbd86f302350b2f070c7c50bb0a0f488e23a435d515e2818a8361fb610301eaa922b9b3e52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
